# Generated by Django 5.2.2 on 2025-06-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0007_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='post_default.png', null=True, upload_to='articulo'),
        ),
    ]
